---
ID: "a873acc4-9047-4a7b-acd1-52762f4b4931"
Parent: "9112014d-54d5-4c5e-b696-92ac51ebb15a"
Template: "9112014d-54d5-4c5e-b696-92ac51ebb15a"
Path: /sitecore/templates/Feature/Navigation/Footer Navigation Links Columns Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{E17A5C79-ED0A-4F95-8A47-CA76322A3C2C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160927T151338Z
