---
ID: "b9670157-5574-42d7-8e63-48eb4f265aa9"
Parent: "61977679-a5da-4791-a6ec-003a99a40ae5"
Template: "61977679-a5da-4791-a6ec-003a99a40ae5"
Path: /sitecore/templates/Feature/Account/Email Preferences/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T083455Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
