---
ID: "98a9ed6e-eca4-4872-a346-e0eac8ae8d9e"
Parent: "66dd30b1-acdb-4562-9041-b6b186237958"
Template: "66dd30b1-acdb-4562-9041-b6b186237958"
Path: /sitecore/templates/Project/Demo/Promo/Multi Promo Container/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4DEE566F-614C-4A89-8F0B-00F4B04BEAB9}"
- ID: "6fd695e7-7f6d-4ca5-8b49-a829e5950ae9"
  Hint: __Subitems Sorting
  Value: 
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161117T194544Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
