---
ID: "503b6e0e-52aa-4cf9-b3b4-787ad3843fc9"
Parent: "e822a1e9-d502-463d-b38c-fdb84b3afabf"
Template: "e822a1e9-d502-463d-b38c-fdb84b3afabf"
Path: /sitecore/templates/Feature/Promo/Multi Promo/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4DEE566F-614C-4A89-8F0B-00F4B04BEAB9}"
- ID: "6fd695e7-7f6d-4ca5-8b49-a829e5950ae9"
  Hint: __Subitems Sorting
  Value: 
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161117T194544Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
