---
ID: "2c98723f-3a88-4072-88cf-db76df400712"
Parent: "80a8ad76-8ee3-483b-a43c-9fe29ca77938"
Template: "80a8ad76-8ee3-483b-a43c-9fe29ca77938"
Path: /sitecore/templates/Feature/Search/Featured Results/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T102403Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
