---
ID: "87e14428-7bb7-43b3-9f63-799d57c0a064"
Parent: "0068beae-cb7c-44ee-a5cb-db6e4668d383"
Template: "0068beae-cb7c-44ee-a5cb-db6e4668d383"
Path: /sitecore/templates/Feature/Page Content/_Date Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161025T135511Z
    - ID: "3927b1aa-347c-4d88-9b93-b327eae1b6d0"
      Hint: Date of Publication
      Value: $date
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
