---
ID: "22de3a0c-c88d-4657-bb31-a99d7814f554"
Parent: "2cbb661f-2029-456e-9ae8-25194c3f425a"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Velir/Search/Filters/Text Filter/Text Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140815T141130
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
