---
ID: "8b966de9-f444-4f71-bca0-15f72d0abfab"
Parent: "8c5b5db5-85de-4b12-aaba-0c112cabfdd0"
Template: "8c5b5db5-85de-4b12-aaba-0c112cabfdd0"
Path: /sitecore/templates/Feature/Navigation/Primary Navigation Links Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {E5ACF52C-1E6B-4142-84F2-6D09B1BA1AB8}
    {D5745F91-8FA1-457F-BE87-875A029C7B69}
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160224T195459Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
