---
ID: "aaf31034-c2e5-4494-a2c4-e4b5a539f9c8"
Parent: "0941e9eb-06e9-415b-aab1-6362dd21afd5"
Template: "0941e9eb-06e9-415b-aab1-6362dd21afd5"
Path: /sitecore/templates/Velir/Search/Sort Options/Sort Options Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{A216F849-A384-46E8-AFAC-05860D8C69C1}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140814T140550
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
