---
ID: "1ba9010b-49f2-43ab-927e-ea318ea08f6d"
Parent: "ec9f61d5-4b55-4e71-8dfa-20a38d7499c2"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Velir/Search/Filters/Boolean Filter/Boolean Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140818T173000
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
