---
ID: "ee5dc520-4117-4d98-81a8-915e4ab71e17"
Parent: "cb803dab-1f25-469b-b5ff-5cea4ac39edd"
Template: "cb803dab-1f25-469b-b5ff-5cea4ac39edd"
Path: /sitecore/templates/Feature/Robots/Robots Configuration/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T101120Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
