---
ID: "c9fb0407-c35b-468f-a2a7-b2e665f69d05"
Parent: "e300d2d2-ab70-4876-9c8a-285c681eaf15"
Template: "e300d2d2-ab70-4876-9c8a-285c681eaf15"
Path: /sitecore/templates/Feature/Metadata/_Index Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T095120Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
