---
ID: "6cb1597f-9d72-41ba-9baf-d813b55ad05b"
Parent: "ca21bb62-10b5-46d5-a713-683c56333fef"
Template: "ca21bb62-10b5-46d5-a713-683c56333fef"
Path: /sitecore/templates/Feature/Global/Footer/_Footer Logo/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161012T121128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ea671236-6b49-48cf-a30a-c18cc97b3be2"
      Hint: Footer Logo
      Value: |
        <image mediaid="{A1999E94-8FF2-42CA-9C71-805A26E5AA83}" />
