---
ID: "72cb6249-a30a-4f8c-9bf6-a9849cf036a2"
Parent: "56c607e1-b07a-47e9-9041-04703acafd3c"
Template: "56c607e1-b07a-47e9-9041-04703acafd3c"
Path: /sitecore/templates/Foundation/Enumerations/Folders/Text Alignment Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{6EB8BC7F-E231-44AD-92B2-B1FBAC97B3B1}"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161109T161642Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
