---
ID: "cbbd352d-1420-4fa7-9ca9-4795efea6a7e"
Parent: "d8017f32-92a9-44f2-b461-1c38d7a5d75d"
Template: "d8017f32-92a9-44f2-b461-1c38d7a5d75d"
Path: /sitecore/templates/Foundation/Taxonomy/Base/_Topic Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T085814Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
