---
ID: "3ce00ce1-0ef3-46cb-ab9b-d0f1b2df92cc"
Parent: "1625996d-32ba-4001-8d85-4072658a8bd0"
Template: "1625996d-32ba-4001-8d85-4072658a8bd0"
Path: /sitecore/templates/Foundation/Enumerations/Folders/Salutations Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{24B98CC6-FC73-4BC4-8B45-A40022047990}"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170310T163457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
