---
ID: "95372287-923a-47a0-b811-b820e7591227"
Parent: "958038af-b23a-4f67-bbf7-879e709d83d2"
Template: "958038af-b23a-4f67-bbf7-879e709d83d2"
Path: /sitecore/templates/Foundation/Taxonomy/Base/_People Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T085845Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
