---
ID: "021c8398-e741-427a-9b62-f6dbcc89955a"
Parent: "3f3a656c-332d-46d6-951e-63fb2d06f8e4"
Template: "3f3a656c-332d-46d6-951e-63fb2d06f8e4"
Path: /sitecore/templates/Feature/Metadata/Metadata Configuration/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T095044Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
