---
ID: "b81b6e53-f5e8-42b1-bab7-66f04c49a997"
Parent: "26b33d54-4f6b-4e86-b3f3-5d25a68c2941"
Template: "26b33d54-4f6b-4e86-b3f3-5d25a68c2941"
Path: /sitecore/templates/Feature/Events/_Event Details/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T092535Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
