---
ID: "043012cf-0c82-47bc-9a15-cf8d997f0a62"
Parent: "e56d528a-b576-4926-85e1-d08acc82fad5"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Velir/Image Cropper/Crop Ratio/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111209T100627
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kmazzoni
