---
ID: "eecd8ea9-76fb-4079-b796-9242ea0178d4"
Parent: "2507ca55-c349-4c83-85c6-13db1d6a5428"
Template: "2507ca55-c349-4c83-85c6-13db1d6a5428"
Path: /sitecore/templates/Foundation/Taxonomy/Base/_Taxonomy Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T085446Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
