---
ID: "3218aeab-5da7-4d39-b466-76a88c8fd740"
Parent: "14e2f690-2849-45f2-9b1f-8741fd0606d0"
Template: "14e2f690-2849-45f2-9b1f-8741fd0606d0"
Path: /sitecore/templates/Feature/Navigation/Breadcrumb Configuration/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170921T172515Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a94cf3ac-75ea-4f48-8299-082a9a1aa413"
      Hint: SVG Delimiter Name
      Value: "chevron-right"
