---
ID: "56562179-1033-4c77-8e29-1d5b554b6abb"
Parent: "1393e28b-2a66-428c-81f9-bbfe01650e48"
Template: "1393e28b-2a66-428c-81f9-bbfe01650e48"
Path: /sitecore/templates/Feature/Multimedia/Image/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161130T171854Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "bc91a53d-f539-4275-b803-05286d41151a"
      Hint: Image
      Value: |
        <image mediaid="{ECD1121C-5433-44E4-81D1-AD708F9DAECC}" />
