---
ID: "5670416e-7f5e-4192-a8d8-d09a6cf16156"
Parent: "60ac7f1a-2dda-4022-8f6c-a75fd3732303"
Template: "60ac7f1a-2dda-4022-8f6c-a75fd3732303"
Path: /sitecore/templates/Feature/Banners/Page Banner/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161107T212637Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8f6bb17a-0d9a-4fb5-b9de-1133ca7cfcd0"
      Hint: Image
      Value: |
        <image mediaid="{AE3A7858-5301-441A-9B5F-224411C8C417}" />
