---
ID: "7d9369a6-b3b2-4706-a36d-29186ef35853"
Parent: "9744d172-190e-49ed-9d2f-b9f588bfeaf9"
Template: "9744d172-190e-49ed-9d2f-b9f588bfeaf9"
Path: /sitecore/templates/Feature/Social/Social Media Link/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T102532Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
