---
ID: "3d928a73-3f0a-4958-925f-8468847a4804"
Parent: "68f0c8d8-72fb-4837-a723-560c6373406b"
Template: "68f0c8d8-72fb-4837-a723-560c6373406b"
Path: /sitecore/templates/Feature/Page Content/_Short Title Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "10e9213f-9aad-4979-a6a4-912a36275bb9"
      Hint: Short title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161025T141428Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
