---
ID: "8ed83617-94d0-4128-97dd-bf89dc320179"
Parent: "66e6c75f-3e19-496d-82ec-cf7af4938722"
Template: "66e6c75f-3e19-496d-82ec-cf7af4938722"
Path: /sitecore/templates/Feature/Social/_Share Configuration/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T102600Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
