---
ID: "469b49fa-16a1-4e3a-8212-243028bb5c95"
Parent: "c8b2d606-72c1-47cb-b4c3-6d27a3976de0"
Template: "c8b2d606-72c1-47cb-b4c3-6d27a3976de0"
Path: /sitecore/templates/Feature/Metadata/_Metadata Base/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T095108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
