---
ID: "eff29a2b-b90f-421f-b44b-5189baa3d417"
Parent: "9d05e174-d4d6-4bd8-a0c1-e0d521e2fb37"
Template: "9d05e174-d4d6-4bd8-a0c1-e0d521e2fb37"
Path: /sitecore/templates/Foundation/Aliases/Alias Site Folder/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190314T191102Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
