---
ID: "e6a99a37-ca9b-4ab4-bcba-76e622ae3ef4"
Parent: "2e317d2b-24ed-4633-87f8-6ccfadb06d93"
Template: "2e317d2b-24ed-4633-87f8-6ccfadb06d93"
Path: /sitecore/templates/Velir/Search/Filters/Sort Strategies/Sort Strategy/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151207T152311Z
    - ID: "32086477-70e7-45b1-a3fe-204b3a73e42d"
      Hint: Type
      Value: Velir.Search.Core.Facets.Sort.NoSortStrategy, Velir.Search.Core
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
