---
ID: "055a7527-4737-4452-9c45-c930d3a6d417"
Parent: "5ccd0fbb-5349-460f-91f1-f1e960cb0e90"
Template: "5ccd0fbb-5349-460f-91f1-f1e960cb0e90"
Path: /sitecore/templates/Velir/Search/Base/_Listing Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "040c0194-6c6e-43fd-ac5c-0aa3daa35a87"
      Hint: Default Sort Order
      Value: "{34BDD660-3780-466E-8BED-E867DE0224C2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170111T162958Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "9f76d8df-ef1c-4b6d-af33-b2655fd0cc74"
      Hint: Items Per Page
      Value: 10
