---
ID: "50767000-078d-4944-8322-1354714a412a"
Parent: "69ed1402-6eaf-46ad-b6d6-c3cf273a6e34"
Template: "69ed1402-6eaf-46ad-b6d6-c3cf273a6e34"
Path: /sitecore/templates/Feature/Account/_Account Configuration/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200917T083540Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
